import { EntryType, EntryStatus } from './types'

export const CATEGORIES = [
  'Contracts',
  'Appointments',
  'Health',
  'Finance',
  'Personal',
  'Events',
  'Friends',
  'Work',
]

export const CATEGORY_MAP = {
  Contracts: EntryType.CONTRACT,
  Appointments: EntryType.APPOINTMENT,
  Health: EntryType.HEALTH,
  Finance: EntryType.FINANCE,
  Personal: EntryType.PERSONAL,
  Events: EntryType.EVENT,
  Friends: EntryType.FRIEND,
  Work: EntryType.WORK,
}

export const INITIAL_ENTRIES = [
  {
    id: '1',
    userId: 'demo-user',
    title: 'Internet Fiber Contract',
    category: 'Contracts',
    status: EntryStatus.ACTIVE,
    type: EntryType.CONTRACT,
    expirationDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    userId: 'demo-user',
    title: 'Health Insurance Premium',
    category: 'Contracts',
    status: EntryStatus.DUE,
    type: EntryType.INSURANCE,
    expirationDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    userId: 'demo-user',
    title: 'Annual Physical Exam',
    category: 'Health',
    status: EntryStatus.ACTIVE,
    type: EntryType.HEALTH,
    startAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    userId: 'demo-user',
    title: 'Dinner with Sarah',
    category: 'Friends',
    status: EntryStatus.ACTIVE,
    type: EntryType.FRIEND,
    startAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    userId: 'demo-user',
    title: 'Q4 Budget Planning',
    category: 'Work',
    status: EntryStatus.DONE,
    type: EntryType.WORK,
    startAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    userId: 'demo-user',
    title: 'Car Insurance Renewal',
    category: 'Contracts',
    status: EntryStatus.ACTIVE,
    type: EntryType.INSURANCE,
    expirationDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const INITIAL_DOCUMENTS = [
  {
    id: 'doc1',
    userId: 'demo-user',
    entryId: '1',
    filename: 'internet_contract.pdf',
    fileUrl: '#',
    mimeType: 'application/pdf',
    uploadedAt: new Date().toISOString(),
  },
  {
    id: 'doc2',
    userId: 'demo-user',
    entryId: '2',
    filename: 'insurance_policy.pdf',
    fileUrl: '#',
    mimeType: 'application/pdf',
    uploadedAt: new Date().toISOString(),
  },
]
